version: 2
jobs:
  test:
    docker:
      - image: python:3.6
    steps:
    - checkout
    - run:
        name: install tox
        command: |
            pip -V
            sudo pip install --upgrade tox==2.1.1
            sudo pip install -U pip
            sudo pip install -U ipdb
            sudo pip install coveralls
            sudo pip install docutils
            sudo pip install check-manifest
            sudo pip install Pygments
            sudo pip install bashtest
    - run:
        name: unit tests
        command: |
            python setup.py check -m -r -s
            python setup.py build
            bashtest --exitcode test_*.bashtest
            bashtest README.rst

  build-linux-binary:
    docker:
      - image: python:3.6
    steps:
      - checkout
      - run:
          name: build Linux binary
          command: ./.circleci/linux_build.sh
      - store_artifacts:
          path: dist/docker-compose-Linux-x86_64
          destination: docker-compose-Linux-x86_64

workflows:
  version: 2
  all:
    jobs:
      - test
      - build-linux-binary
