version: 2
jobs:
  test:
    docker:
      - image: python:3.6
    working_directory: ~/repo
    steps:
    - checkout
    - run:
        name: install
        command: |
            pip -V
            pip install --upgrade tox==2.1.1
            pip install -U pip
            pip install -U ipdb
            pip install virtualenv
            pip install coveralls
            pip install docutils
            pip install check-manifest
            pip install Pygments
            pip install bashtest
    - run:
        name: tests
        command: |
            python setup.py check -m -r -s
            python setup.py build
            bashtest --exitcode test_*.bashtest
            bashtest README.rst

  build-linux-binary:
    docker:
      - image: python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install
          command: |
              pip -V
              pip install --upgrade tox==2.1.1
              pip install -U pip
              pip install -U ipdb
              pip install virtualenv
              pip install coveralls
              pip install docutils
              pip install check-manifest
              pip install Pygments
              pip install bashtest
      - run:
          name: build Linux binary
          command: ./.circleci/linux_build.sh
      - store_artifacts:
          path: dist/py3line-Linux-x86_64
          destination: py3line-Linux-x86_64

workflows:
  version: 2
  all:
    jobs:
      - test
      - build-linux-binary
